[package]
edition = "2021"
name = "cube"
version = "0.1.0"

[dependencies]
eframe = "0.21.3"
once_cell = "1"
parking_lot = "0.12.1"

[dependencies.hodaun]
features = ["notes", "output", "noise"]
version = "0.2.3"

[dependencies.rand]
features = ["small_rng"]
version = "0.8.5"
